export {
  AuthFailures,
  BetterAuthConfigurationError,
  BetterAuthInfrastructureError,
  getRawCause,
  isAuthFailure,
  isConfigurationError,
  isInfrastructureError,
} from "./auth-errors.js";
export type {
  AuthErrorBody,
  AuthErrorCode,
  AuthFailure,
  AuthGraphqlExtensions,
  AuthTransportErrorPayload,
  ErrorMappingOptions,
} from "./auth-errors.js";
export type {
  ApplicationRouteDescriptor,
  AdvisedHandler,
  AuthContextView,
  AuthHandle,
  AuthHandlerInterceptor,
  AuthPrincipalBase,
  AuthorizationContext,
  AuthorizationDecision,
  AuthorizationLimits,
  AuthorizationPolicy,
  AuthRouteBinding,
  AuthTransport,
  BetterAuthAppOptions,
  BetterAuthFactoryResult,
  BetterAuthModuleAsyncOptions,
  BetterAuthModuleOptions,
  BetterAuthRuntimeOptions,
  BetterAuthStaticOptions,
  BootAdvice,
  BootAdviceContext,
  BrowserExposure,
  ClaimOptions,
  CookieForwardingOptions,
  CookieSink,
  CorsOriginOptions,
  DatabaseHookTarget,
  DbHookMethodDecorator,
  DbHookOptions,
  DefaultInstanceCheck,
  ExtensionDefinition,
  ExtensionRef,
  GuardReach,
  HookMethodDecorator,
  HookOptions,
  HookPredicate,
  HttpMountOptions,
  HttpPlatform,
  HttpRequestAccessor,
  InboundAuthRequest,
  InvocationLineage,
  OriginCheckOptions,
  PlatformMountContext,
  PlatformPrepareContext,
  PolicyBootContext,
  PolicyInvoker,
  PolicyRef,
  PrincipalDelegation,
  PrincipalReading,
  PrincipalRequest,
  PrincipalResolver,
  PrincipalResult,
  PrincipalSource,
  ProxyTrust,
  Requirement,
  RequirementExpr,
  RequirementOptions,
  ResolutionRequest,
  RoutePlan,
  ScopeInit,
  SessionOption,
  SessionPrincipalOptions,
  StaticOptionMustBePassedToForRootAsync,
  TransportCall,
  TransportKit,
  TransportValidationContext,
} from "./auth-contracts.js";
export {
  getBetterAuthHandleToken,
  getBetterAuthInstanceToken,
  getBetterAuthOptionsToken,
  getBetterAuthServiceToken,
} from "./auth-tokens.js";
export type {
  AuthAfterHookContext,
  AuthHookContext,
  AuthLike,
  AuthOf,
  AuthPrincipal,
  AuthSession,
  AuthUser,
  DatabaseHookData,
  DatabaseHookMethod,
  DatabaseHookResult,
  EndpointPath,
  GetSessionWithHeaders,
  IsRegistered,
  PrincipalKind,
  PrincipalKinds,
  PrincipalOfKind,
  Register,
  RegisteredAuth,
  RegisteredInstances,
  SessionOf,
  SessionPrincipal,
  UnvalidatedBody,
  UserOf,
  WithActiveOrganization,
} from "./auth-types.js";

export { BetterAuthModule } from "./auth-module.js";
export { BetterAuthService } from "./auth-service.js";
export { BetterAuthGuard } from "./auth-guard.js";
export { BetterAuthScopeInterceptor } from "./auth-scope-interceptor.js";
export {
  defineExtension,
  defineHttpPlatform,
  defineTransport,
} from "./auth-module-definition.js";
export { EXTENSION_DEFINITION } from "./bridge-protocol.js";
export {
  GUARD_CORE,
  SCOPE_CORE,
  PRINCIPAL_RESOLVER,
  POLICY_INVOKER,
} from "./auth-tokens.js";
export {
  AcceptPrincipals,
  AfterAuth,
  AfterDatabase,
  BeforeAuth,
  BeforeDatabase,
  CurrentPrincipal,
  ForwardAuthCookies,
  OptionalAuth,
  Public,
  Require,
  RequireAuth,
  SkipDefaultRequirements,
  SkipOriginCheck,
  UseAuthInstance,
  UseBetterAuth,
  allOf,
  anyOf,
  defineInvocationParam,
  definePrincipalParam,
  requirement,
} from "./auth-decorators.js";
export {
  CurrentSession,
  CurrentUser,
  RequireFreshSession,
  SESSION_PRINCIPAL_KIND,
  freshSession,
  sessionPrincipal,
} from "./session-principal.js";
export {
  absent,
  authenticated,
  definePrincipalSource,
  rejected,
} from "./principal-resolver.js";
export { allow, definePolicy, deny } from "./authorization-evaluator.js";
export { betterAuthCorsOrigin } from "./auth-exchange.js";
export { httpTransport } from "./http-transport.js";
